FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ejercicio_app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ejercicio_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ejercicio_app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ejercicio_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ejercicio_app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ejercicio_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ejercicio_app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ejercicio_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ejercicio_app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ejercicio_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ejercicio_app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ejercicio_app.py
FROM python
RUN pip install flask
COPY ./static /home/myapp/static/
COPY ./templates /home/myapp/templates/
COPY ejercicio_app.py /home/myapp/
EXPOSE 5050
CMD python3 /home/myapp/ejercicio_app.py
FROM python:3
WORKDIR
COPY requirements.txt ./
RUN pip install flask
COPY ./static ./static/
COPY ./templates ./templates/
COPY ejercicio_app.py ./
RUN pip install --no-cache-dir -r requirements.txt 
EXPOSE 5050
CMD python /ejercicio_app.py
FROM python:3
WORKDIR
COPY requirements.txt ./
RUN pip install flask
COPY ./static ./static/
COPY ./templates ./templates/
COPY ejercicio_app.py ./
RUN pip install --no-cache-dir -r requirements.txt 
EXPOSE 5050
CMD python /ejercicio_app.py
